version: "3.8"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store 
    ports:
      - "5432:5432"
    volumes:
      - ./docker/createDatabase:/docker-entrypoint-initdb.d
    networks:
      - store

networks:
  store:
    driver: bridge